version: '3.8'

services:
  flask-app-1:
    image: ${DOCKER_USERNAME}/devopsapp:${TAG_APP1}
    restart: always
    ports:
      - "8001:5000" # Maps VM host port 8001 to container port 5000

  flask-app-2:
    image: ${DOCKER_USERNAME}/devopsapp:${TAG_APP2}
    restart: always
    ports:
      - "8002:5000" # Maps VM host port 8002 to container port 5000